apiVersion: v1
kind: Service
metadata:
  name: configuration-server
  namespace: sweetify
spec:
  ports:
    - port: 8888
  selector:
    app: configuration-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-server
  namespace: sweetify
  labels:
    app: configuration-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration-server
  template:
    metadata:
      labels:
        app: configuration-server
    spec:
      containers:
        - name: configuration-server
          image: frcalderon/sweetify-configuration-server
          imagePullPolicy: Always
          env:
             - name: SPRING_PROFILES_ACTIVE
               value: prod
             - name: EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE
               value: http://discovery-server:8761/eureka/