apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30080
  selector:
    app: gateway

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: api-gateway
          image: frcalderon/api-gateway:1.0.0
          imagePullPolicy: Always
          env:
            # - name: SPRING_PROFILES_ACTIVE
            #   value: development
            - name: DISCOVERY_SERVER_URL
              value: http://discovery-server:8761/eureka
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - name: KEYCLOAK_REALM_URL
              value: http://kube:8081/realms/demo
            - name: KEYCLOAK_CLIENT_ID
              value: demo-client
            - name: KEYCLOAK_CLIENT_SECRET
              value: Bld3vbSxaLKn7IK2YxFCUur832gyAUfN
            - name: KEYCLOAK_REDIRECT_URL
              value: http://kube:8080/login/oauth2/demo-client