kind: ConfigMap
apiVersion: v1
metadata:
  name: ms-products
  namespace: sweetify
data:
  application.yml: |-
    server:
      port: 8080
    spring:
      application:
        name: ms-products
      profiles:
        active:
          - prod
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://keycloak:8080/realms/sweetify
      datasource:
        url: jdbc:postgresql://products-db:5432/products
        username: admin
        password: admin
        driver-class-name: org.postgresql.Driver
      jpa:
        database: POSTGRESQL
        hibernate:
          ddl-auto: update
        show-sql: true

---

apiVersion: v1
kind: Service
metadata:
  name: ms-products
  namespace: sweetify
spec:
  ports:
    - port: 8080
  selector:
    app: ms-products

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-products
  namespace: sweetify
  labels:
    app: ms-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-products
  template:
    metadata:
      labels:
        app: ms-products
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - name: ms-products
          image: frcalderon/sweetify-ms-products
          imagePullPolicy: Always
          env:
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "true"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-ms-products
  namespace: sweetify
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-products
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50